id: P000411
initial_creation_type: ocr
created_at: 18/03/2020
last_modified_at: 2021-12-16 15:38:33.757851
source_metadata:
  id: bdr:W1KG1629
  title: དགེ་ལྡན་མཁས་གྲུབ་དག་གི་རྫོགས་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    a78d20aec10b4cb8af7cbcefe0c6de1c:
      image_group_id: I1KG1631
      title: Volume 1 of dge ldan mkhas grub dag gi rdzogs skor phyogs bsgrigs
      volume_number: 1
      total_pages: 308
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
